### ISSUE TITLE
Error when running the demo

### ISSUE THREAD

**Issue by jaredsmith** [Igalia/gst-wpe-webrtc-demo#1]
I'm trying to reproduce your demo on my local system.  I have the NodeJS app running, and it seem to be working OK.  I have the wpe plugin for GStreamer installed, and I have verified that it is also working correctly.

When I try to run the Rust program, however, I get the following error:

[jsmith@server gst-wpe-webrtc-demo]$ cargo run --release -- -s ws://192.168.55.180:8188 -r 1234 -f 42
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/gst-wpe-webrtc-demo -s 'ws://192.168.55.180:8188' -r 1234 -f 42`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/pipeline.rs:135:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by philn** [comment]
Which version of GStreamer are you using?

**Comment by jaredsmith** [comment]
I'm using 1.17.90... but I think I figured out my issue.  My test system was missing the "nice" plugin for GStreamer.  Once I installed that, the demo worked as expected :-)

**Comment by philn** [comment]
Cool! Have fun! Don't hesitate to reach out if you have more questions :)

**Comment by Niko-La** [comment]
Hi this is such a cool demo.  I am having trouble running wpesrc.  Didnt want to open another issue if its just a simple thing I am doing wrong.  Any advice woul be much appreciated. 

![image](https://user-images.githubusercontent.com/14004559/101536512-1bc1cd80-3968-11eb-8ad1-52bfcd6638c6.png)


uname -a
Linux linuxnikola-P67X-UD3-B3 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by philn** [comment]
@Niko-La which Ubuntu version are you using? `wpesrc` is packaged separately, see https://packages.ubuntu.com/groovy/gstreamer1.0-wpe
You might find a PPA hosting backports, sorry I can't help much, I haven't used Ubuntu in years ;)

BTW I see the "discussion" thing seems to be available in beta now, I will enable it for this project.

**Comment by Niko-La** [comment]
@philn I am on Ubuntu 20.10  Happy to get this going can improve the documentation.  This is the most popular distro so it would be great to detail this step.

Please recommend PPA link.

**Comment by philn** [comment]
Sorry I don't have time for this currently. If you find one, please open a new thread in the "discussions" of this project. Discussing here is not optimal.
